### ISSUE TITLE
Marvel Nemesis - Rise of the Imperfects (USA) missing health bars

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#287]
during the gameplay your player is missing the health bars 
![marvel](https://user-images.githubusercontent.com/2696404/48964189-26a5a180-efdd-11e8-880a-35dab587d365.PNG)

**Comment by StapleButter** [comment]
notes on this:

* can't reproduce on latest revision! apparently caused by the GX timing revision. it just hangs before entering any fight. I think we're running into core timing issues that were offset/compensated by the bad GX timings.
* NO$GBA exhibits the same bug. appears the rotscale data for those sprites is crapoed?

**Comment by StapleButter** [comment]
fix0red the regression, now we can get to this bug, I guess

**Comment by StapleButter** [comment]
aha.

seems it's using windows to restrict the visible parts of the health bars
