### ISSUE TITLE
Call of Duty 4 - Modern Warfare (USA) graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#68]
during the intro the top screen has graphic glitches

**Comment by StapleButter** [comment]
would be nice if you were more precise and/or provided a screenshot

**Comment by scottluker** [comment]
![2017-06-14_09-16-23](https://user-images.githubusercontent.com/8451624/27122434-929f9954-50e2-11e7-996d-77485d93bdf7.png)
![2017-06-14_09-16-35](https://user-images.githubusercontent.com/8451624/27122435-92c71650-50e2-11e7-8766-1b4d7606380f.png)

Just to help out,

**Comment by DarkSwan86** [comment]
Still present on ad58a68

**Comment by StapleButter** [comment]
fun side note on this bug:

unlike what I first thought, the red tones weren't coming from the 3D engine. they come from BG3 which is a red halo.

BLDCNT is set such that BG3 will blend with the 3D graphics. the issue was that under these circumstances, the second-target check wasn't using the right value (as for the 3D layer, pixel alpha is stored there instead of the usual layer mask). as a result, the layer would blend only wherever the 3D alpha was odd (bit0 set), and be completely opaque on the rest of the screen.

disabling fog first appeared to fix the issue, because fog alters the final 3D alpha values. without it they're all 31 and the bug goes unnoticed.
