### ISSUE TITLE
Etrian Odyssey 1 cannot load saves created in melonDS

### ISSUE THREAD

**Issue by JMC47** [StapleButter/melonDS#89]
I'm guessing this is another issue with selecting the right savetype.

**Comment by JMC47** [comment]
Here's the savefile it created for what it is worth.

[Etrian Odyssey.zip](https://github.com/StapleButter/melonDS/files/1132879/Etrian.Odyssey.zip)

**Comment by JMC47** [comment]
Loading the savefile into another emulator reveals it's at least recognized, but, a lot of the settings aren't what I set, and all of my character data is gone.

**Comment by JMC47** [comment]
The savefile made in melonDS is 8KB, while the Medusa savefile I made was 64KB.

**Comment by StapleButter** [comment]
medusa resizes its savefile as needed instead of trying to guess the size and enforcing it. The issue of that method is that there are games that try to read/write out of bounds as an anti-piracy measure.

melonDS on the other hand, runs into this kind of issues. I guess I'll just use a database. The heuristics are a mess already.

**Comment by StapleButter** [comment]
this should be fixed, too
